language: haskell
before_install:
  - cabal install codecov-haskell
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test  --exclude-dir=test test
after_script:
  - codecov-haskell --exclude-dir=test test