language: haskell
before_install:
  - cabal install codecov-haskell
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test test
after_script:
  - codecov-haskell --display-report --print-response --exclude-dir=test --token=cf9633d2-a2bf-4087-927c-62b57194044e test