language: haskell
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - cabal install codecov-haskell
  - codecov-haskell test --exclude-dir=test